var sybtitles=Array();
var sybgrouptitles=Array();

function setgroup(base, value) {
	for (j=0; j<16; j++) {
		hex=j.toString(16);
		sybtitles[base+hex]=value+" ("+j+")";
		sybgrouptitles[base]=value;
	}
}

for (i=0; i<256; i++) {
	for (j=0; j<16; j++) {
		celltypehex=(i*16+j+0x1000).toString(16).substr(-3);
		sybtitles[celltypehex]='Material '+i+" meta "+j;
	}
}

setgroup("00", "air");
setgroup("01", "stone");
sybtitles["011"]="granite";
sybtitles["012"]="polished granite";
sybtitles["013"]="diorite";
sybtitles["014"]="polished diorite";
sybtitles["015"]="andesite";
sybtitles["016"]="polished andesite";

setgroup("02", "grass");
setgroup("03", "dirt");
setgroup("04", "cobblestone");
setgroup("05", "planks");
sybtitles["050"]="Oak planks";
sybtitles["051"]="Spruce planks";
sybtitles["052"]="Birch planks";
sybtitles["053"]="Jungle planks";
sybtitles["054"]="Acacia planks";
sybtitles["055"]="Dark Oak planks";

setgroup("06", "sapling");
setgroup("07", "bedrock");
setgroup("08", "flowing_water");
setgroup("09", "water");
setgroup("0a", "flowing_lava");
setgroup("0b", "lava");
setgroup("0c", "sand");
setgroup("0d", "gravel");
setgroup("0e", "gold_ore");
setgroup("0f", "iron_ore");
setgroup("10", "coal_ore");
setgroup("11", "log");
setgroup("12", "leaves");
setgroup("13", "sponge");
setgroup("14", "glass");
setgroup("15", "lapis_ore");
setgroup("16", "lapis_block");
setgroup("17", "dispenser");
setgroup("18", "sandstone");
setgroup("19", "noteblock");
setgroup("1a", "bed");
setgroup("1b", "golden_rail");
setgroup("1c", "detector_rail");
setgroup("1d", "sticky_piston");
setgroup("1e", "web");
setgroup("1f", "tallgrass");
setgroup("20", "deadbush");
setgroup("21", "piston");
setgroup("22", "piston_head");
setgroup("23", "wool");
setgroup("24", "piston_extension");
setgroup("25", "yellow_flower");
setgroup("26", "red_flower");
setgroup("27", "brown_mushroom");
setgroup("28", "red_mushroom");
setgroup("29", "gold_block");
setgroup("2a", "iron_block");
setgroup("2b", "double_stone_slab");
setgroup("2c", "stone_slab");
setgroup("2d", "brick_block");
setgroup("2e", "tnt");
setgroup("2f", "bookshelf");
setgroup("30", "mossy_cobblestone");
setgroup("31", "obsidian");
setgroup("32", "torch");
setgroup("33", "fire");
setgroup("34", "mob_spawner");
setgroup("35", "oak_stairs");
setgroup("36", "chest");
setgroup("37", "redstone_wire");
setgroup("38", "diamond_ore");
setgroup("39", "diamond_block");
setgroup("3a", "crafting_table");
setgroup("3b", "wheat");
setgroup("3c", "farmland");
setgroup("3d", "furnace");
setgroup("3e", "lit_furnace");
setgroup("3f", "standing_sign");
setgroup("40", "wooden_door");
setgroup("41", "ladder");
setgroup("42", "rail");
setgroup("43", "stone_stairs");
setgroup("44", "wall_sign");
setgroup("45", "lever");
setgroup("46", "stone_pressure_plate");
setgroup("47", "iron_door");
setgroup("48", "wooden_pressure_plate");
setgroup("49", "redstone_ore");
setgroup("4a", "lit_redstone_ore");
setgroup("4b", "unlit_redstone_torch");
setgroup("4c", "redstone_torch");
setgroup("4d", "stone_button");
setgroup("4e", "snow_layer");
setgroup("4f", "ice");
setgroup("50", "snow");
setgroup("51", "cactus");
setgroup("52", "clay");
setgroup("53", "reeds");
setgroup("54", "jukebox");
setgroup("55", "fence");
setgroup("56", "pumpkin");
setgroup("57", "netherrack");
setgroup("58", "soul_sand");
setgroup("59", "glowstone");
setgroup("5a", "portal");
setgroup("5b", "lit_pumpkin");
setgroup("5c", "cake");
setgroup("5d", "unpowered_repeater");
setgroup("5e", "powered_repeater");
setgroup("5f", "stained_glass");
setgroup("60", "trapdoor");
setgroup("61", "monster_egg");
setgroup("62", "stonebrick");
setgroup("63", "brown_mushroom_block");
setgroup("64", "red_mushroom_block");
setgroup("65", "iron_bars");
setgroup("66", "glass_pane");
setgroup("67", "melon_block");
setgroup("68", "pumpkin_stem");
setgroup("69", "melon_stem");
setgroup("6a", "vine");
setgroup("6b", "fence_gate");
setgroup("6c", "brick_stairs");
setgroup("6d", "stone_brick_stairs");
setgroup("6e", "mycelium");
setgroup("6f", "waterlily");
setgroup("70", "nether_brick");
setgroup("71", "nether_brick_fence");
setgroup("72", "nether_brick_stairs");
setgroup("73", "nether_wart");
setgroup("74", "enchanting_table");
setgroup("75", "brewing_stand");
setgroup("76", "cauldron");
setgroup("77", "end_portal");
setgroup("78", "end_portal_frame");
setgroup("79", "end_stone");
setgroup("7a", "dragon_egg");
setgroup("7b", "redstone_lamp");
setgroup("7c", "lit_redstone_lamp");
setgroup("7d", "double_wooden_slab");
setgroup("7e", "wooden_slab");
setgroup("7f", "cocoa");
setgroup("80", "sandstone_stairs");
setgroup("81", "emerald_ore");
setgroup("82", "ender_chest");
setgroup("83", "tripwire_hook");
setgroup("84", "tripwire");
setgroup("85", "emerald_block");
setgroup("86", "spruce_stairs");
setgroup("87", "birch_stairs");
setgroup("88", "jungle_stairs");
setgroup("89", "command_block");
setgroup("8a", "beacon");
setgroup("8b", "cobblestone_wall");
setgroup("8c", "flower_pot");
setgroup("8d", "carrots");
setgroup("8e", "potatoes");
setgroup("8f", "wooden_button");
setgroup("90", "skull");
setgroup("91", "anvil");
setgroup("92", "trapped_chest");
setgroup("93", "light_weighted_pressure_plate");
setgroup("94", "heavy_weighted_pressure_plate");
setgroup("95", "unpowered_comparator");
setgroup("96", "powered_comparator");
setgroup("97", "daylight_detector");
setgroup("98", "redstone_block");
setgroup("99", "quartz_ore");
setgroup("9a", "hopper");
sybtitles["9a0"]="Hopper facing down";
sybtitles["9a1"]="Hopper facing up";
sybtitles["9a2"]="Hopper facing north";
sybtitles["9a3"]="Hopper facing south";
sybtitles["9a4"]="Hopper facing west";
sybtitles["9a5"]="Hopper facing east";

setgroup("9b", "quartz_block");
setgroup("9c", "quartz_stairs");
setgroup("9d", "activator_rail");
setgroup("9e", "dropper");
setgroup("9f", "stained_hardened_clay");
setgroup("a0", "stained_glass_pane");
setgroup("a1", "leaves2");
setgroup("a2", "log2");
setgroup("a3", "acacia_stairs");
setgroup("a4", "dark_oak_stairs");
setgroup("a5", "slime");
setgroup("a6", "barrier");
setgroup("a7", "iron_trapdoor");
setgroup("a8", "prismarine");
setgroup("a9", "sea_lantern");
setgroup("aa", "hay_block");
setgroup("ab", "carpet");
setgroup("ac", "hardened_clay");
setgroup("ad", "coal_block");
setgroup("ae", "packed_ice");
setgroup("af", "double_plant");
setgroup("b0", "standing_banner");
setgroup("b1", "wall_banner");
setgroup("b2", "daylight_detector_inverted");
setgroup("b3", "red_sandstone");
setgroup("b4", "red_sandstone_stairs");
setgroup("b5", "double_stone_slab2");
setgroup("b6", "stone_slab2");
setgroup("b7", "spruce_fence_gate");
setgroup("b8", "birch_fence_gate");
setgroup("b9", "jungle_fence_gate");
setgroup("ba", "dark_oak_fence_gate");
setgroup("bb", "acacia_fence_gate");
setgroup("bc", "spruce_fence");
setgroup("bd", "birch_fence");
setgroup("be", "jungle_fence");
setgroup("bf", "dark_oak_fence");
setgroup("c0", "acacia_fence");
setgroup("c1", "spruce_door");
setgroup("c2", "birch_door");
setgroup("c3", "jungle_door");
setgroup("c4", "acacia_door");
setgroup("c5", "dark_oak_door");
setgroup("c6", "end_rod");
setgroup("c7", "chorus_plant");
setgroup("c8", "chorus_flower");
setgroup("c9", "purpur_block");
setgroup("ca", "purpur_pillar");
setgroup("cb", "purpur_stairs");
setgroup("cc", "purpur_double_slab");
setgroup("cd", "purpur_slab");
setgroup("ce", "end_bricks");
setgroup("cf", "beetroots");
setgroup("d0", "grass_path");
setgroup("d1", "end_gateway");
setgroup("d2", "repeating_command_block");
setgroup("d3", "chain_command_block");
setgroup("d4", "frosted_ice");
setgroup("ff", "structure_block");
